---
# Todo:
# Create the required group(s) and user(s) for the application
# Enable the Ubuntu univers repository for "Ubuntu jammy"
# Optionally allow for updating and upgrading the operating system

...
