---
- name: start mariadb
  ansible.builtin.service:
    name: mariadb
    enabled: true
    state: started

- name: restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted
...
